// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contrib/envoy/extensions/filters/network/kubedb_dam_policy/v3/kubedb_dam_policy.proto

package kubedb_dam_policyv3

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRule_Action int32

const (
	// Debug-log only.
	PolicyRule_LOG PolicyRule_Action = 0
	// Emit a counter + stamp the match into dynamic metadata; do not
	// interfere with the connection.
	PolicyRule_ALERT PolicyRule_Action = 1
	// Drop the connection. Surfaces to the client as the protocol-appropriate
	// disconnect (Postgres FATAL, MySQL CR_SERVER_LOST, MongoDB
	// MongoNetworkError, Oracle ORA-03113).
	PolicyRule_DENY PolicyRule_Action = 2
)

// Enum value maps for PolicyRule_Action.
var (
	PolicyRule_Action_name = map[int32]string{
		0: "LOG",
		1: "ALERT",
		2: "DENY",
	}
	PolicyRule_Action_value = map[string]int32{
		"LOG":   0,
		"ALERT": 1,
		"DENY":  2,
	}
)

func (x PolicyRule_Action) Enum() *PolicyRule_Action {
	p := new(PolicyRule_Action)
	*p = x
	return p
}

func (x PolicyRule_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyRule_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes[0].Descriptor()
}

func (PolicyRule_Action) Type() protoreflect.EnumType {
	return &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes[0]
}

func (x PolicyRule_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyRule_Action.Descriptor instead.
func (PolicyRule_Action) EnumDescriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescGZIP(), []int{1, 0}
}

type PolicyRule_Severity int32

const (
	PolicyRule_INFO     PolicyRule_Severity = 0
	PolicyRule_LOW      PolicyRule_Severity = 1
	PolicyRule_MEDIUM   PolicyRule_Severity = 2
	PolicyRule_HIGH     PolicyRule_Severity = 3
	PolicyRule_CRITICAL PolicyRule_Severity = 4
)

// Enum value maps for PolicyRule_Severity.
var (
	PolicyRule_Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	PolicyRule_Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x PolicyRule_Severity) Enum() *PolicyRule_Severity {
	p := new(PolicyRule_Severity)
	*p = x
	return p
}

func (x PolicyRule_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyRule_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes[1].Descriptor()
}

func (PolicyRule_Severity) Type() protoreflect.EnumType {
	return &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes[1]
}

func (x PolicyRule_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyRule_Severity.Descriptor instead.
func (PolicyRule_Severity) EnumDescriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescGZIP(), []int{1, 1}
}

type KubeDbDamPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dynamic-metadata namespaces to merge into the CEL “request“ activation,
	// in declared order (last write wins on conflicting keys). Typically a
	// single entry naming the upstream protocol filter, e.g.
	// “envoy.filters.network.postgres_proxy“. Listing multiple is supported
	// for chains where more than one filter contributes (a session-tracker
	// filter ahead of the protocol filter, for instance).
	SourceFilterMetadata []string `protobuf:"bytes,1,rep,name=source_filter_metadata,json=sourceFilterMetadata,proto3" json:"source_filter_metadata,omitempty"`
	// CEL rules. Evaluated in declared order. Per spec §9.1 explicit-deny-wins:
	// a single matching Deny short-circuits enforcement, even if earlier Allow
	// / Log / Alert rules also matched on the same query.
	Rules []*PolicyRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	// Simulation mode: matches still record metrics and the “simulated_match“
	// metadata flag, but Deny is not enforced. Safe staging for new rule sets
	// (spec §9.5).
	SimulationMode bool `protobuf:"varint,3,opt,name=simulation_mode,json=simulationMode,proto3" json:"simulation_mode,omitempty"`
	// “request.env.*“ fields the control plane pre-computes and pushes into
	// the activation. Spec §9.2 calls out:
	//
	//	env.now                — timestamp; auto-populated, do not set here.
	//	env.business_hours     — bool; pre-computed against the operating cal.
	//	env.maintenance_window — bool; pre-computed against MaintenanceWindow.
	//	env.timezone           — string, e.g. "Asia/Dhaka".
	//	env.cluster            — logical cluster identifier.
	//
	// Beyond those, anything the control plane wants to expose to rules can be
	// added here — e.g. “unmask_roles: ["dba", "compliance_auditor"]“ makes
	// the spec §9.4.3 mask-bypass rule expressible as
	// “role in request.env.unmask_roles“ without needing a custom CEL
	// function. Same pattern for PAM allowlists, vendor identity lists, etc.
	//
	// The struct is merged verbatim into “request.env“ at evaluation time.
	// Fields here override anything the upstream protocol filter wrote under
	// an “env“ key in its dynamic metadata.
	EnvFields     *structpb.Struct `protobuf:"bytes,4,opt,name=env_fields,json=envFields,proto3" json:"env_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeDbDamPolicy) Reset() {
	*x = KubeDbDamPolicy{}
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeDbDamPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeDbDamPolicy) ProtoMessage() {}

func (x *KubeDbDamPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeDbDamPolicy.ProtoReflect.Descriptor instead.
func (*KubeDbDamPolicy) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescGZIP(), []int{0}
}

func (x *KubeDbDamPolicy) GetSourceFilterMetadata() []string {
	if x != nil {
		return x.SourceFilterMetadata
	}
	return nil
}

func (x *KubeDbDamPolicy) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *KubeDbDamPolicy) GetSimulationMode() bool {
	if x != nil {
		return x.SimulationMode
	}
	return false
}

func (x *KubeDbDamPolicy) GetEnvFields() *structpb.Struct {
	if x != nil {
		return x.EnvFields
	}
	return nil
}

type PolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable rule identifier surfaced in audit events, metrics labels
	// (“kubedb_dam_policy.rule_matches{rule_id=...}“), and dynamic metadata.
	// Typically the spec/clause reference, e.g. “bb-ict-5.9.3-cardholder-allowlist“.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Free-text description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// CEL expression returning bool. Evaluated against the PolicyRequest
	// activation (spec §9.2). Compile errors at config-load time are surfaced
	// as Envoy config validation errors so a bad rule never reaches the data
	// plane.
	When     string              `protobuf:"bytes,3,opt,name=when,proto3" json:"when,omitempty"`
	Action   PolicyRule_Action   `protobuf:"varint,4,opt,name=action,proto3,enum=envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule_Action" json:"action,omitempty"`
	Severity PolicyRule_Severity `protobuf:"varint,5,opt,name=severity,proto3,enum=envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule_Severity" json:"severity,omitempty"`
	// Optional CEL expression returning a string. When the rule matches, the
	// string is stamped onto dynamic metadata under
	// “envoy.filters.network.kubedb_dam_policy.matches[N].reason“. Convenient
	// for surfacing the spec clause + relevant request fields back to the audit
	// pipeline.
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyRule) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *PolicyRule) GetAction() PolicyRule_Action {
	if x != nil {
		return x.Action
	}
	return PolicyRule_LOG
}

func (x *PolicyRule) GetSeverity() PolicyRule_Severity {
	if x != nil {
		return x.Severity
	}
	return PolicyRule_INFO
}

func (x *PolicyRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto protoreflect.FileDescriptor

const file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDesc = "" +
	"\n" +
	"Ucontrib/envoy/extensions/filters/network/kubedb_dam_policy/v3/kubedb_dam_policy.proto\x125envoy.extensions.filters.network.kubedb_dam_policy.v3\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x95\x02\n" +
	"\x0fKubeDbDamPolicy\x12>\n" +
	"\x16source_filter_metadata\x18\x01 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x14sourceFilterMetadata\x12a\n" +
	"\x05rules\x18\x02 \x03(\v2A.envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRuleB\b\xfaB\x05\x92\x01\x02\b\x01R\x05rules\x12'\n" +
	"\x0fsimulation_mode\x18\x03 \x01(\bR\x0esimulationMode\x126\n" +
	"\n" +
	"env_fields\x18\x04 \x01(\v2\x17.google.protobuf.StructR\tenvFields\"\xb1\x03\n" +
	"\n" +
	"PolicyRule\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\x04when\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04when\x12`\n" +
	"\x06action\x18\x04 \x01(\x0e2H.envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.ActionR\x06action\x12f\n" +
	"\bseverity\x18\x05 \x01(\x0e2J.envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.SeverityR\bseverity\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"&\n" +
	"\x06Action\x12\a\n" +
	"\x03LOG\x10\x00\x12\t\n" +
	"\x05ALERT\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02\"A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04B\xdf\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Cio.envoyproxy.envoy.extensions.filters.network.kubedb_dam_policy.v3B\x14KubedbDamPolicyProtoP\x01Zxgithub.com/envoyproxy/go-control-plane/contrib/envoy/extensions/filters/network/kubedb_dam_policy/v3;kubedb_dam_policyv3b\x06proto3"

var (
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescOnce sync.Once
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescData []byte
)

func file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescGZIP() []byte {
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescOnce.Do(func() {
		file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDesc)))
	})
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDescData
}

var file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_goTypes = []any{
	(PolicyRule_Action)(0),   // 0: envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.Action
	(PolicyRule_Severity)(0), // 1: envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.Severity
	(*KubeDbDamPolicy)(nil),  // 2: envoy.extensions.filters.network.kubedb_dam_policy.v3.KubeDbDamPolicy
	(*PolicyRule)(nil),       // 3: envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule
	(*structpb.Struct)(nil),  // 4: google.protobuf.Struct
}
var file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_depIdxs = []int32{
	3, // 0: envoy.extensions.filters.network.kubedb_dam_policy.v3.KubeDbDamPolicy.rules:type_name -> envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule
	4, // 1: envoy.extensions.filters.network.kubedb_dam_policy.v3.KubeDbDamPolicy.env_fields:type_name -> google.protobuf.Struct
	0, // 2: envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.action:type_name -> envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.Action
	1, // 3: envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.severity:type_name -> envoy.extensions.filters.network.kubedb_dam_policy.v3.PolicyRule.Severity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_init()
}
func file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_init() {
	if File_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_goTypes,
		DependencyIndexes: file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_depIdxs,
		EnumInfos:         file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_enumTypes,
		MessageInfos:      file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_msgTypes,
	}.Build()
	File_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto = out.File
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_goTypes = nil
	file_contrib_envoy_extensions_filters_network_kubedb_dam_policy_v3_kubedb_dam_policy_proto_depIdxs = nil
}
