// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mysql_proxy.proto

package mysql_proxyv3

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/trace/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MySQLProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The human readable prefix to use when emitting :ref:`statistics
	// <config_network_filters_mysql_proxy_stats>`.
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// [#not-implemented-hide:] The optional path to use for writing MySQL access logs.
	// If the access log field is empty, access logs will not be written.
	AccessLog              string           `protobuf:"bytes,2,opt,name=access_log,json=accessLog,proto3" json:"access_log,omitempty"`
	AuditLog               *v3.Tracing_Http `protobuf:"bytes,3,opt,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	TerminateDownstreamTls bool             `protobuf:"varint,4,opt,name=terminate_downstream_tls,json=terminateDownstreamTls,proto3" json:"terminate_downstream_tls,omitempty"`
	UpstreamTls            bool             `protobuf:"varint,5,opt,name=upstream_tls,json=upstreamTls,proto3" json:"upstream_tls,omitempty"`
	// Controls whether SQL statements received in Frontend Query messages
	// are decoded. Defaults to true.
	EnableDecoding *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=enable_decoding,json=enableDecoding,proto3" json:"enable_decoding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MySQLProxy) Reset() {
	*x = MySQLProxy{}
	mi := &file_mysql_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLProxy) ProtoMessage() {}

func (x *MySQLProxy) ProtoReflect() protoreflect.Message {
	mi := &file_mysql_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLProxy.ProtoReflect.Descriptor instead.
func (*MySQLProxy) Descriptor() ([]byte, []int) {
	return file_mysql_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *MySQLProxy) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *MySQLProxy) GetAccessLog() string {
	if x != nil {
		return x.AccessLog
	}
	return ""
}

func (x *MySQLProxy) GetAuditLog() *v3.Tracing_Http {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

func (x *MySQLProxy) GetTerminateDownstreamTls() bool {
	if x != nil {
		return x.TerminateDownstreamTls
	}
	return false
}

func (x *MySQLProxy) GetUpstreamTls() bool {
	if x != nil {
		return x.UpstreamTls
	}
	return false
}

func (x *MySQLProxy) GetEnableDecoding() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableDecoding
	}
	return nil
}

var File_mysql_proxy_proto protoreflect.FileDescriptor

const file_mysql_proxy_proto_rawDesc = "" +
	"\n" +
	"\x11mysql_proxy.proto\x12/envoy.extensions.filters.network.mysql_proxy.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\x1a'envoy/config/trace/v3/http_tracer.proto\"\xfd\x02\n" +
	"\n" +
	"MySQLProxy\x12(\n" +
	"\vstat_prefix\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"statPrefix\x12\x1d\n" +
	"\n" +
	"access_log\x18\x02 \x01(\tR\taccessLog\x12@\n" +
	"\taudit_log\x18\x03 \x01(\v2#.envoy.config.trace.v3.Tracing.HttpR\bauditLog\x128\n" +
	"\x18terminate_downstream_tls\x18\x04 \x01(\bR\x16terminateDownstreamTls\x12!\n" +
	"\fupstream_tls\x18\x05 \x01(\bR\vupstreamTls\x12C\n" +
	"\x0fenable_decoding\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x0eenableDecoding:B\x9aň\x1e=\n" +
	";envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxyB\xc8\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"=io.envoyproxy.envoy.extensions.filters.network.mysql_proxy.v3B\x0fMysqlProxyProtoP\x01Zlgithub.com/envoyproxy/go-control-plane/contrib/envoy/extensions/filters/network/mysql_proxy/v3;mysql_proxyv3b\x06proto3"

var (
	file_mysql_proxy_proto_rawDescOnce sync.Once
	file_mysql_proxy_proto_rawDescData []byte
)

func file_mysql_proxy_proto_rawDescGZIP() []byte {
	file_mysql_proxy_proto_rawDescOnce.Do(func() {
		file_mysql_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mysql_proxy_proto_rawDesc), len(file_mysql_proxy_proto_rawDesc)))
	})
	return file_mysql_proxy_proto_rawDescData
}

var file_mysql_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mysql_proxy_proto_goTypes = []any{
	(*MySQLProxy)(nil),           // 0: envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
	(*v3.Tracing_Http)(nil),      // 1: envoy.config.trace.v3.Tracing.Http
	(*wrapperspb.BoolValue)(nil), // 2: google.protobuf.BoolValue
}
var file_mysql_proxy_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy.audit_log:type_name -> envoy.config.trace.v3.Tracing.Http
	2, // 1: envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy.enable_decoding:type_name -> google.protobuf.BoolValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mysql_proxy_proto_init() }
func file_mysql_proxy_proto_init() {
	if File_mysql_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mysql_proxy_proto_rawDesc), len(file_mysql_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mysql_proxy_proto_goTypes,
		DependencyIndexes: file_mysql_proxy_proto_depIdxs,
		MessageInfos:      file_mysql_proxy_proto_msgTypes,
	}.Build()
	File_mysql_proxy_proto = out.File
	file_mysql_proxy_proto_goTypes = nil
	file_mysql_proxy_proto_depIdxs = nil
}
