// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contrib/envoy/extensions/filters/network/kubedb_dam_audit/v3/kubedb_dam_audit.proto

package kubedb_dam_auditv3

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [#protodoc-title: KubeDB-DAM audit log sink]
//
// Engine-agnostic audit sink for the KubeDB-DAM stack (spec §7).
// The filter sits in the listener filter chain AFTER every DAM-emitting
// filter (kubedb_dam_mssql / oracle_proxy / postgres_proxy / mysql_proxy
// / mongo_proxy / kubedb_dam_redis / kubedb_dam_session /
// kubedb_dam_policy). On every read and write pass, it inspects the
// connection's dynamic metadata under each “watched_namespace“ and
// emits a JSON line to “log_path“ whenever the namespace's metadata
// envelope changed since the last emission for that namespace on this
// connection.
//
// Output line format (one per envelope, newline-terminated)::
//
//	{"ts":"<RFC3339>", "ns":"<namespace>",
//	 "conn_id":<int>, "envelope": <full ProtobufStruct as JSON>}
//
// File rotation / reopen-on-SIGHUP is delegated to Envoy's access log
// manager (“AccessLogManager::createAccessLog“), so the same
// operational tooling that handles existing access logs applies here.
//
// [#extension: envoy.filters.network.kubedb_dam_audit]
type KubeDbDamAudit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stat prefix used for the emitted counters
	// (“kubedb_dam_audit.<stat_prefix>.*“).
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// Filesystem path to append audit records to. Each record is one JSON
	// object on its own line. Envoy's access log manager opens the file
	// in append mode and reopens on SIGHUP.
	//
	// Set to empty string to disable the built-in file sink — useful
	// when “access_logs“ carries all the configured destinations.
	LogPath string `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	// Dynamic-metadata namespaces to watch. Each one is typically a DAM
	// filter name, e.g. “envoy.filters.network.kubedb_dam_mssql“. The
	// audit filter reads each namespace's struct on every onData /
	// onWrite pass, fingerprints the canonical JSON form, and emits a
	// line when the fingerprint differs from the last emission for that
	// namespace.
	//
	// An empty list disables the filter (it becomes a no-op pass-through).
	WatchedNamespaces []string `protobuf:"bytes,3,rep,name=watched_namespaces,json=watchedNamespaces,proto3" json:"watched_namespaces,omitempty"`
	// Drop records whose envelope's “request.query.risk_score“ is below
	// this value. 0 = no filtering. Caps at 100 (the saturation point of
	// the detector packs).
	MinRiskScore uint32 `protobuf:"varint,4,opt,name=min_risk_score,json=minRiskScore,proto3" json:"min_risk_score,omitempty"`
	// When true, only emit records whose envelope has “risk_alert ==
	// true“. Implicitly requires that the upstream DAM filter is
	// emitting the field (every DAM filter in this fork does, with the
	// alert-threshold default of 50).
	OnlyOnAlert bool `protobuf:"varint,5,opt,name=only_on_alert,json=onlyOnAlert,proto3" json:"only_on_alert,omitempty"`
	// When true, only emit records whose envelope has “risk_block ==
	// true“. The strictest filter — by spec semantics this is the set
	// of envelopes that triggered (or would trigger) a DENY decision by
	// a downstream policy filter.
	OnlyOnBlock bool `protobuf:"varint,6,opt,name=only_on_block,json=onlyOnBlock,proto3" json:"only_on_block,omitempty"`
	// Additional Envoy access-log sinks fired on each envelope change
	// (after dedup + filtering). Lets operators stream DAM events to
	// gRPC, OpenTelemetry, Fluentd, or any other access-log factory
	// registered in the binary — in addition to (or instead of) the
	// built-in file sink at “log_path“.
	//
	// Each AccessLog is invoked with a default “Formatter::Context“
	// and the connection's StreamInfo. The access logger's own format
	// string (typically using “%DYNAMIC_METADATA(...)%“ directives)
	// determines what shows up in the sink; this filter only triggers
	// the emission at the right moment.
	//
	// The built-in “log_path“ file sink remains active when configured
	// alongside “access_logs“. Set “log_path“ to "" to disable it
	// and use only the configured access logs.
	AccessLogs    []*v3.AccessLog `protobuf:"bytes,7,rep,name=access_logs,json=accessLogs,proto3" json:"access_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeDbDamAudit) Reset() {
	*x = KubeDbDamAudit{}
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeDbDamAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeDbDamAudit) ProtoMessage() {}

func (x *KubeDbDamAudit) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeDbDamAudit.ProtoReflect.Descriptor instead.
func (*KubeDbDamAudit) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescGZIP(), []int{0}
}

func (x *KubeDbDamAudit) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *KubeDbDamAudit) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *KubeDbDamAudit) GetWatchedNamespaces() []string {
	if x != nil {
		return x.WatchedNamespaces
	}
	return nil
}

func (x *KubeDbDamAudit) GetMinRiskScore() uint32 {
	if x != nil {
		return x.MinRiskScore
	}
	return 0
}

func (x *KubeDbDamAudit) GetOnlyOnAlert() bool {
	if x != nil {
		return x.OnlyOnAlert
	}
	return false
}

func (x *KubeDbDamAudit) GetOnlyOnBlock() bool {
	if x != nil {
		return x.OnlyOnBlock
	}
	return false
}

func (x *KubeDbDamAudit) GetAccessLogs() []*v3.AccessLog {
	if x != nil {
		return x.AccessLogs
	}
	return nil
}

var File_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto protoreflect.FileDescriptor

const file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDesc = "" +
	"\n" +
	"Scontrib/envoy/extensions/filters/network/kubedb_dam_audit/v3/kubedb_dam_audit.proto\x124envoy.extensions.filters.network.kubedb_dam_audit.v3\x1a)envoy/config/accesslog/v3/accesslog.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xc2\x02\n" +
	"\x0eKubeDbDamAudit\x12(\n" +
	"\vstat_prefix\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"statPrefix\x12\x19\n" +
	"\blog_path\x18\x02 \x01(\tR\alogPath\x12-\n" +
	"\x12watched_namespaces\x18\x03 \x03(\tR\x11watchedNamespaces\x12-\n" +
	"\x0emin_risk_score\x18\x04 \x01(\rB\a\xfaB\x04*\x02\x18dR\fminRiskScore\x12\"\n" +
	"\ronly_on_alert\x18\x05 \x01(\bR\vonlyOnAlert\x12\"\n" +
	"\ronly_on_block\x18\x06 \x01(\bR\vonlyOnBlock\x12E\n" +
	"\vaccess_logs\x18\a \x03(\v2$.envoy.config.accesslog.v3.AccessLogR\n" +
	"accessLogsB\xdb\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Bio.envoyproxy.envoy.extensions.filters.network.kubedb_dam_audit.v3B\x13KubedbDamAuditProtoP\x01Zvgithub.com/envoyproxy/go-control-plane/contrib/envoy/extensions/filters/network/kubedb_dam_audit/v3;kubedb_dam_auditv3b\x06proto3"

var (
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescOnce sync.Once
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescData []byte
)

func file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescGZIP() []byte {
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescOnce.Do(func() {
		file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDesc)))
	})
	return file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDescData
}

var file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_goTypes = []any{
	(*KubeDbDamAudit)(nil), // 0: envoy.extensions.filters.network.kubedb_dam_audit.v3.KubeDbDamAudit
	(*v3.AccessLog)(nil),   // 1: envoy.config.accesslog.v3.AccessLog
}
var file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.filters.network.kubedb_dam_audit.v3.KubeDbDamAudit.access_logs:type_name -> envoy.config.accesslog.v3.AccessLog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_init()
}
func file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_init() {
	if File_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_goTypes,
		DependencyIndexes: file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_depIdxs,
		MessageInfos:      file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_msgTypes,
	}.Build()
	File_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto = out.File
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_goTypes = nil
	file_contrib_envoy_extensions_filters_network_kubedb_dam_audit_v3_kubedb_dam_audit_proto_depIdxs = nil
}
