// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contrib/envoy/extensions/filters/network/mssql_proxy/v3/mssql_proxy.proto

package mssql_proxyv3

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSSQLProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string helloField = 1;
	TerminateSsl  *bool `protobuf:"varint,1,opt,name=terminate_ssl,json=terminateSsl,proto3,oneof" json:"terminate_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSSQLProxy) Reset() {
	*x = MSSQLProxy{}
	mi := &file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSSQLProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSSQLProxy) ProtoMessage() {}

func (x *MSSQLProxy) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSSQLProxy.ProtoReflect.Descriptor instead.
func (*MSSQLProxy) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *MSSQLProxy) GetTerminateSsl() bool {
	if x != nil && x.TerminateSsl != nil {
		return *x.TerminateSsl
	}
	return false
}

var File_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto protoreflect.FileDescriptor

const file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDesc = "" +
	"\n" +
	"Icontrib/envoy/extensions/filters/network/mssql_proxy/v3/mssql_proxy.proto\x12/envoy.extensions.filters.network.mssql_proxy.v3\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"H\n" +
	"\n" +
	"MSSQLProxy\x12(\n" +
	"\rterminate_ssl\x18\x01 \x01(\bH\x00R\fterminateSsl\x88\x01\x01B\x10\n" +
	"\x0e_terminate_sslB\xc8\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"=io.envoyproxy.envoy.extensions.filters.network.mssql_proxy.v3B\x0fMSSQLProxyProtoP\x01Zlgithub.com/envoyproxy/go-control-plane/contrib/envoy/extensions/filters/network/mssql_proxy/v3;mssql_proxyv3b\x06proto3"

var (
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescOnce sync.Once
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescData []byte
)

func file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescGZIP() []byte {
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescOnce.Do(func() {
		file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDesc)))
	})
	return file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDescData
}

var file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_goTypes = []any{
	(*MSSQLProxy)(nil), // 0: envoy.extensions.filters.network.mssql_proxy.v3.MSSQLProxy
}
var file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_init() }
func file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_init() {
	if File_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto != nil {
		return
	}
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_goTypes,
		DependencyIndexes: file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_depIdxs,
		MessageInfos:      file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_msgTypes,
	}.Build()
	File_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto = out.File
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_goTypes = nil
	file_contrib_envoy_extensions_filters_network_mssql_proxy_v3_mssql_proxy_proto_depIdxs = nil
}
