// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: contrib/envoy/extensions/filters/network/oracle_proxy/v3/oracle_proxy.proto

package oracle_proxyv3

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OracleProxy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TerminateDownstreamTls *bool                  `protobuf:"varint,1,opt,name=terminate_downstream_tls,json=terminateDownstreamTls,proto3,oneof" json:"terminate_downstream_tls,omitempty"`
	UpstreamTls            *bool                  `protobuf:"varint,2,opt,name=upstream_tls,json=upstreamTls,proto3,oneof" json:"upstream_tls,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OracleProxy) Reset() {
	*x = OracleProxy{}
	mi := &file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleProxy) ProtoMessage() {}

func (x *OracleProxy) ProtoReflect() protoreflect.Message {
	mi := &file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleProxy.ProtoReflect.Descriptor instead.
func (*OracleProxy) Descriptor() ([]byte, []int) {
	return file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *OracleProxy) GetTerminateDownstreamTls() bool {
	if x != nil && x.TerminateDownstreamTls != nil {
		return *x.TerminateDownstreamTls
	}
	return false
}

func (x *OracleProxy) GetUpstreamTls() bool {
	if x != nil && x.UpstreamTls != nil {
		return *x.UpstreamTls
	}
	return false
}

var File_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto protoreflect.FileDescriptor

const file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDesc = "" +
	"\n" +
	"Kcontrib/envoy/extensions/filters/network/oracle_proxy/v3/oracle_proxy.proto\x120envoy.extensions.filters.network.oracle_proxy.v3\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\xa2\x01\n" +
	"\vOracleProxy\x12=\n" +
	"\x18terminate_downstream_tls\x18\x01 \x01(\bH\x00R\x16terminateDownstreamTls\x88\x01\x01\x12&\n" +
	"\fupstream_tls\x18\x02 \x01(\bH\x01R\vupstreamTls\x88\x01\x01B\x1b\n" +
	"\x19_terminate_downstream_tlsB\x0f\n" +
	"\r_upstream_tlsB\xcc\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	">io.envoyproxy.envoy.extensions.filters.network.oracle_proxy.v3B\x10OracleProxyProtoP\x01Zngithub.com/envoyproxy/go-control-plane/contrib/envoy/extensions/filters/network/oracle_proxy/v3;oracle_proxyv3b\x06proto3"

var (
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescOnce sync.Once
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescData []byte
)

func file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescGZIP() []byte {
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescOnce.Do(func() {
		file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDesc)))
	})
	return file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDescData
}

var file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_goTypes = []any{
	(*OracleProxy)(nil), // 0: envoy.extensions.filters.network.oracle_proxy.v3.OracleProxy
}
var file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_init() }
func file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_init() {
	if File_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto != nil {
		return
	}
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDesc), len(file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_goTypes,
		DependencyIndexes: file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_depIdxs,
		MessageInfos:      file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_msgTypes,
	}.Build()
	File_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto = out.File
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_goTypes = nil
	file_contrib_envoy_extensions_filters_network_oracle_proxy_v3_oracle_proxy_proto_depIdxs = nil
}
